name: Multiple Jobs
on: push
env:
  username: Supriya
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Supriya
      - run: echo 'Hi ${{ env.username }}'  # Hi Saurabh
        env:
          username: Octocat
  linux_job:
    runs-on: ubuntu-latest
    env:
      username: Tux
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Gaurav
